/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button, NativeModules, NativeEventEmitter } from 'react-native';
import MopSDK, { Config, FinStoreConfig, BOOLState, LanguageType, FCReLaunchMode, UIConfig } from 'react-native-mopsdk';
const onPressOpenCanvasApplet = () => {
  MopSDK.openApplet({ appId: '5facb3a52dcbff00017469bd' }).then((res) => {
    console.log('openApplet success: ', res);
  }).catch((error) => {
    console.log('openApplet error: ', error);
  });
};
const onPressOpenDemoApplet = () => {
  // MopSDK.openApplet({ appId: '5f72e3559a6a7900019b5baa' });
  MopSDK.startApplet({appletId:'64c23309c533620001a1971e', startParams:{'query':'abcd'}, reLaunchMode: FCReLaunchMode.Never})
};
const onPressOpenTestApplet = () => {
  MopSDK.openApplet({ appId: '5f17f457297b540001e06ebb' });
};

const onPressCustomMenu = () => {
  MopSDK.registerAppletHandler({
    getCustomMenus(appId) {
      console.log("getCustomMenus")
      return []
    }
  })
};

const onPressFinishAll = () => {
  MopSDK.finishAllRunningApplets();
}
export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {

    const eventEmitter = new NativeEventEmitter(NativeModules.FINMopSDK);

    let finStoreConfigA = new FinStoreConfig(
      "22LyZEib0gLTQdU3MUauATBwgfnTCJjdr7FCnywmAEM=",
      "bdfd76cae24d4313",
      "https://api.finclip.com");

    let finStoreConfigs = [finStoreConfigA];
    let config = new Config(finStoreConfigs,{language:LanguageType.Chinese,userId:"123456789",debug:true,appletDebugMode:BOOLState.BOOLStateTrue}) ;
    let uiConfig = new UIConfig({isHideClearCacheMenu:true});
    let params = {
      config: config,
      uiConfig: uiConfig,
      finMopSDK: NativeModules.FINMopSDK,
      nativeEventEmitter: eventEmitter
    }

    MopSDK.initSDK(params).then((res) => {
      console.log('message: ', res);
      const s = JSON.stringify(res);
      this.setState({
        status: 'native callback received',
        message: s,
      });
    }).catch((error) => {
      console.log('init error: ', error);
      const s = 'initialize fail'
      this.setState({
        status: 'native callback received',
        message: s,
      });
    })
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆FINMopsdk example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Button
          onPress={onPressOpenCanvasApplet}
          title="打开画图小程序"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
        <Button
          onPress={onPressOpenDemoApplet}
          title="打开官方小程序"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
        <Button
          onPress={onPressOpenTestApplet}
          title="打开测试小程序"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
        <Button
          onPress={onPressFinishAll}
          title="结束所有小程序"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
        <Button
          onPress={onPressCustomMenu}
          title="自定义菜单"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
